changed 5-mysql_backup

diff --git a/0x14-mysql/5-mysql_backup b/0x14-mysql/5-mysql_backup
--- a/0x14-mysql/5-mysql_backup
+++ b/0x14-mysql/5-mysql_backup
@@ -1,31 +1,26 @@
 #!/usr/bin/env bash
 # Bash script that generates a MySQL dump and creates a compressed archive out of it.
 
-if [ "$#" -ne 1 ]; then
-        echo "Usage: $0 <mysql_root_password>"
-        exit 1
-fi
-
-mysql_root_password="$1"
-
-time=$(date +%d-%m-%Y)
-
-destination="backup.sql"
-archive_name="${time}.tar.gz"
-
-sudo mysqldump -u root  --all-databases > "${destination}"
-
-if [ $? -ne 0 ]; then
-        echo "Error: MySQL dump failed."
-        exit 1
-fi
-
+# if [ "$#" -ne 1 ]; then
+#        echo "Usage: $0 <mysql_root_password>"
+#        exit 1
+# fi
+# mysql_root_password="$1"
+# time=$(date +%d-%m-%Y)
+# destination="backup.sql"
+# archive_name="${time}.tar.gz"
+# sudo mysqldump -u root  --all-databases > "${destination}"
+# if [ $? -ne 0 ]; then
+#        echo "Error: MySQL dump failed."
+#        exit 1
+# fi
 # gzip > "${destination}"
-tar -cvzf "${archive_name}" "${destination}"
+# tar -cvzf "${archive_name}" "${destination}"
+# if [ $? -ne 0 ]; then
+#        echo "Error: Archive creation failed."
+#        exit 1
+# fi
+# echo "Backup completed successfully. Archive: ${archive_name}"
+mysqldump -uroot -p"$1" --all-databases > backup.sql
+tar -cvzf "$(date +%d-%m-%Y)".tar.gz backup.sql
 
-if [ $? -ne 0 ]; then
-        echo "Error: Archive creation failed."
-        exit 1
-fi
-
-echo "Backup completed successfully. Archive: ${archive_name}"
